### ISSUE TITLE
Remove all previous routes. 

### ISSUE THREAD

**Issue by petrubocsanean** [FilledStacks/stacked_services#1]
Hi, on a successfull login scenario there would be a need to remove all previous routes from the stack. So it would be nice to have support for pushNamedAndRemoveUntil() method on navigation service.

**Comment by FilledStacks** [comment]
Yes, this service is very basic at the moment. I’ll add that functionality tomorrow and push it up. I have to move over a lot of functionality from our production apps but I'll add this in and push it soon.

**Comment by petrubocsanean** [comment]
Thanks !

**Comment by FilledStacks** [comment]
@petrubocsanean  v 0.2.0 has all the updates with some additional functionality exposed as well. Sorry for taking so long, I had some other code things to take care of first.
